import React from 'react';
import './privacy.css';

const Privacy = () => {
  return (
    <div className="privacy-container">
      <div className="privacy-content">
        <h1>Privacy Policy</h1>

        <div className="policy-meta">
          <p><strong>Effective Date:</strong> March 1, 2026<br />
          <strong>Last Updated:</strong> March 1, 2026</p>
        </div>

        <section className="policy-section">
          <h2>Introduction</h2>
          <p>Hillsboro LLC ("we," "our," or "us") operates the Jaspen web application (the "Service"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our Service.</p>
          <p>By using Jaspen, you agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with our practices, do not use the Service.</p>
        </section>

        <section className="policy-section">
          <h2>Information We Collect</h2>

          <h3>Account Information</h3>
          <ul>
            <li><strong>Registration Data:</strong> Name, email address, and authentication credentials provided through our supported sign-in methods</li>
            <li><strong>Profile Information:</strong> Display name, preferences, and account settings you configure</li>
            <li><strong>Billing Data:</strong> Subscription plan, credit usage, and payment history (payment processing is handled by Stripe; we do not store full credit card numbers)</li>
          </ul>

          <h3>Project and Session Data</h3>
          <ul>
            <li><strong>Conversation Content:</strong> Messages, project descriptions, and business information you provide during analysis sessions</li>
            <li><strong>Analysis Results:</strong> Strategy scorecards, market IQ scores, scenario models, and financial projections generated by the Service</li>
            <li><strong>Session Metadata:</strong> Session timestamps, completion status, readiness scores, and analysis history</li>
            <li><strong>Uploaded Files:</strong> Documents and files you attach during conversations</li>
          </ul>

          <h3>Usage Information</h3>
          <ul>
            <li><strong>Service Interactions:</strong> Features used, pages visited, and actions taken within the application</li>
            <li><strong>Device Information:</strong> Browser type, operating system, and screen resolution</li>
            <li><strong>Log Data:</strong> IP addresses, access times, and referring URLs</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>AI Data Processing</h2>
          <p>Jaspen uses AI models to analyze your input and generate strategy scorecards, scores, and recommendations. When you interact with the Service:</p>
          <ul>
            <li>Your conversation content is sent to AI service providers for processing</li>
            <li>AI providers process your data to generate responses and are contractually prohibited from using your data for model training</li>
            <li>Generated outputs (scores, analyses) are stored in your account for continued access</li>
            <li>We do not use your project-specific data to train or fine-tune AI models</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>How We Use Your Information</h2>
          <p>We use collected information to:</p>
          <ul>
            <li>Provide, maintain, and improve the Service</li>
            <li>Process your analyses and generate strategy scorecards</li>
            <li>Manage your account, billing, and credit allocation</li>
            <li>Send service-related communications (billing confirmations, feature updates)</li>
            <li>Monitor and analyze usage patterns to improve the platform</li>
            <li>Detect, prevent, and address technical issues and security threats</li>
            <li>Comply with legal obligations</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>Data Retention</h2>
          <ul>
            <li><strong>Account Data:</strong> Retained for the duration of your account plus a reasonable period after deletion for legal compliance</li>
            <li><strong>Session Data:</strong> Analysis sessions and scorecards are retained as long as your account is active</li>
            <li><strong>Billing Records:</strong> Retained as required by tax and financial regulations</li>
            <li><strong>Usage Logs:</strong> Retained for up to 12 months for analytics and security purposes</li>
          </ul>
          <p>You may request deletion of your data at any time by contacting us.</p>
        </section>

        <section className="policy-section">
          <h2>Third-Party Services</h2>
          <p>We use the following third-party services to operate Jaspen:</p>
          <ul>
            <li><strong>Stripe:</strong> Payment processing for subscriptions and credit pack purchases. Stripe's privacy policy governs how they handle your payment information.</li>
            <li><strong>Authentication Providers:</strong> We use third-party authentication services for secure sign-in. These providers receive only the minimum data necessary for authentication.</li>
            <li><strong>AI Service Providers:</strong> Your conversation data is processed by AI providers to generate analyses. These providers are bound by data processing agreements.</li>
            <li><strong>Hosting and Infrastructure:</strong> Our application and data are hosted on secure cloud infrastructure with industry-standard protections.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>Cookies and Tracking</h2>
          <p>Jaspen uses essential cookies to maintain your session and preferences. We may also use:</p>
          <ul>
            <li><strong>Authentication Cookies:</strong> To keep you signed in across sessions</li>
            <li><strong>Preference Cookies:</strong> To remember your display settings and configurations</li>
            <li><strong>Analytics:</strong> To understand how the Service is used and identify areas for improvement</li>
          </ul>
          <p>You can manage cookie preferences through your browser settings. Disabling essential cookies may affect Service functionality.</p>
        </section>

        <section className="policy-section">
          <h2>Your Rights</h2>
          <p>You have the right to:</p>
          <ul>
            <li><strong>Access:</strong> Request a copy of the personal data we hold about you</li>
            <li><strong>Correction:</strong> Update or correct inaccurate personal information</li>
            <li><strong>Deletion:</strong> Request deletion of your personal data, subject to legal retention requirements</li>
            <li><strong>Export:</strong> Request a portable copy of your data</li>
            <li><strong>Opt-out:</strong> Unsubscribe from non-essential communications</li>
          </ul>
          <p>To exercise these rights, contact us at <a href="mailto:hello@jaspen.ai">hello@jaspen.ai</a>.</p>
        </section>

        <section className="policy-section">
          <h2>Data Security</h2>
          <p>We implement industry-standard security measures to protect your data, including encryption in transit and at rest, access controls, and regular security assessments. However, no method of electronic transmission or storage is completely secure, and we cannot guarantee absolute security.</p>
        </section>

        <section className="policy-section">
          <h2>Children's Privacy</h2>
          <p>Jaspen is not directed at individuals under the age of 16. We do not knowingly collect personal information from children. If we learn that we have collected data from a child under 16, we will take steps to delete it promptly.</p>
        </section>

        <section className="policy-section">
          <h2>International Users</h2>
          <p>Jaspen is operated from the United States. If you access the Service from outside the United States, your information may be transferred to and processed in the United States, where data protection laws may differ from those in your jurisdiction.</p>
        </section>

        <section className="policy-section">
          <h2>Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. Material changes will be communicated through the Service or via email. The "Last Updated" date at the top reflects the most recent revision.</p>
        </section>

        <hr className="policy-divider" />

        <section className="policy-section">
          <h2>Contact Us</h2>
          <div className="contact-info">
            <p><strong>Hillsboro LLC</strong><br />
            Email: <a href="mailto:hello@jaspen.ai">hello@jaspen.ai</a><br />
            Website: <a href="https://jaspen.ai" target="_blank" rel="noopener noreferrer">jaspen.ai</a></p>
          </div>
        </section>

        <div className="policy-footer">
          <p>Your privacy is important to us. We are committed to protecting the information you share with Jaspen.</p>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
