"""RFP response Decision Kit v1. Data only; no executable methodology."""

KIT = {
    "key": "rfp_bid",
    "version": 1,
    "label": "RFP response",
    "description": "Bid / No-Bid evaluation for an RFP response.",
    "changelog": ["v1: initial RFP response methodology thresholds."],
    "fields": [
        {"key": "client", "label": "Client / customer", "type": "text", "role": "identity"},
        {"key": "opportunity_ref", "label": "Opportunity reference", "type": "text"},
        {"key": "submission_due", "label": "Submission due", "type": "date", "role": "plan_deadline", "affects": ["delivery_capability_capacity", "submission_deadline"]},
        {"key": "questions_due", "label": "Questions due", "type": "date", "role": "milestone"},
        {"key": "award_expected", "label": "Expected award", "type": "date"},
        {"key": "contract_value", "label": "Contract value", "type": "money", "unit": "USD", "affects": ["financial_attractiveness"]},
        {"key": "build_out_cost", "label": "Build-out cost", "aliases": ["buildout_cost"], "type": "money", "unit": "USD", "affects": ["financial_attractiveness", "delivery_capability_capacity"]},
        {"key": "contract_term_months", "label": "Contract term", "type": "number", "unit": "months"},
        {"key": "award_method", "label": "Award method", "type": "enum"},
        {"key": "win_probability", "label": "Win probability", "type": "percentage", "affects": ["win_probability_competitive_position", "financial_attractiveness"]},
        {"key": "win_probability_basis", "label": "Win probability basis", "type": "text"},
        {"key": "margin_pct", "label": "Expected margin", "type": "percentage", "affects": ["financial_attractiveness"]},
        {"key": "pursuit_cost", "label": "Pursuit cost", "type": "money", "unit": "USD", "affects": ["financial_attractiveness"]},
        {"key": "pursuit_effort_fte_weeks", "label": "Pursuit effort", "type": "number", "unit": "FTE-weeks"},
        {"key": "capacity_draw", "label": "Capacity / bonding draw", "type": "money", "unit": "USD", "affects": ["delivery_capability_capacity", "capacity_available"]},
        {"key": "surety_status", "label": "Surety / bond status", "type": "enum", "affects": ["delivery_capability_capacity", "surety_confirmation"]},
        {"key": "incumbent", "label": "Incumbent", "type": "text"},
        {"key": "competitors", "label": "Competitors", "type": "list"},
        {"key": "relationship", "label": "Relationship", "type": "enum"},
        {"key": "mandatory_requirements", "label": "Mandatory requirements", "type": "list", "role": "requirements", "affects": ["qualifications_past_performance"]},
        {"key": "team", "label": "Pursuit team", "type": "team", "role": "owners", "affects": ["delivery_capability_capacity"]},
    ],
    "starter_rubric": [
        {"key": "win_probability_competitive_position", "label": "Win probability & competitive position", "weight": 0.20},
        {"key": "financial_attractiveness", "label": "Financial attractiveness", "weight": 0.20},
        {"key": "delivery_capability_capacity", "label": "Delivery capability & capacity", "weight": 0.20},
        {"key": "qualifications_past_performance", "label": "Qualifications & past performance", "weight": 0.15},
        {"key": "strategic_fit_relationship", "label": "Strategic fit & relationship", "weight": 0.15},
        {"key": "contract_commercial_risk", "label": "Contract & commercial risk", "weight": 0.10, "is_risk": True},
    ],
    "gate_suggestions": [
        {"key": "submission_deadline", "label": "Able to submit by deadline", "rule": "submission_due can be met"},
        {
            "key": "capacity_available",
            "label": "Capacity / bonding available",
            "rule": "capacity_draw is within available capacity",
            "fact_key": "surety_status",
            "evidence_fields": ["surety_status", "capacity_draw", "mandatory_requirements"],
            "status_values": {"confirmed": "pass", "declined": "fail", "pending": "unknown"},
        },
        {
            "key": "surety_confirmation",
            "label": "Surety / bond confirmation",
            "rule": "surety can support the required bond",
            "fact_key": "surety_status",
            "evidence_fields": ["surety_status", "mandatory_requirements"],
            "status_values": {
                "confirmed": "pass",
                "declined": "fail",
                "pending": "unknown",
            },
        },
    ],
    "metrics": [
        {"key": "expected_value", "label": "Expected margin", "formula": "expected_value", "inputs": ["contract_value", "win_probability", "margin_pct"]},
        {"key": "pursuit_roi", "label": "Pursuit ROI", "formula": "ratio", "inputs": ["metric:expected_value", "pursuit_cost"]},
        {"key": "expected_value_per_fte_week", "label": "Expected margin per FTE-week", "formula": "per_unit", "inputs": ["metric:expected_value", "pursuit_effort_fte_weeks"]},
    ],
    "verdict_vocabulary": {"advance": "Bid", "advance_with_conditions": "Bid with conditions", "decline": "No-Bid"},
    "verdict_thresholds": {"version": 1, "advance_min_score": 60, "decline_below_score": 45, "min_confidence_pct": 55, "close_call_margin": 5},
    "tradeoff_columns": ["win_probability", "contract_value", "metric:expected_value", "pursuit_cost", "submission_due", "gates"],
    "quadrant_axes": {"x": "win_probability", "y": "metric:expected_value"},
    "plan_bindings": {"deadline": "submission_due", "milestone": "questions_due", "requirements": ["mandatory_requirements"], "commitment_template": "Submit the proposal for {client}"},
    "selection": {"objective_metric": "expected_value"},
    "interviewer_hints": ["win probability and its basis", "expected margin", "pursuit cost", "submission deadline"],
}
