export const ARTICLES = [
  {
    slug: 'true-cost-of-home-ownership',
    title: 'What Is the True Monthly Cost of Owning a Home?',
    eyebrow: 'Personal finance',
    description: 'Separate the lender payment, the cost of carrying the home, cash to close, and equity—because one headline number cannot answer four different questions.',
    calculatorPath: '/tools/mortgage-calculator',
    calculatorLabel: 'Home ownership calculator',
    author: { name: 'Grant Ellis', role: 'Sr. Account Executive' },
    readingTime: '7 min read',
    listeningTime: '11 min listen',
    audioPath: '/article-review-narration/true-cost-of-home-ownership.mp3',
    railPoints: ['Required payment', 'True carrying cost', 'Cash to close', 'Equity built'],
  },
  {
    slug: 'true-cost-of-renting',
    title: 'What Does Rent Actually Cost Each Month?',
    eyebrow: 'Personal finance',
    description: 'See past advertised rent to concessions, recurring fees, utilities, move-in cash, and the portion of a deposit that is not automatically a cost.',
    calculatorPath: '/tools/rent-calculator',
    calculatorLabel: 'Rent calculator',
    author: { name: 'Grant Ellis', role: 'Sr. Account Executive' },
    readingTime: '6 min read',
    listeningTime: '7 min listen',
    audioPath: '/article-review-narration/true-cost-of-renting.mp3',
    railPoints: ['Effective rent', 'Recurring costs', 'Move-in cash', 'Refundable deposits'],
  },
  {
    slug: 'cost-of-employee-turnover',
    title: 'Employee Turnover Cost: Beyond the Flat Salary Multiple',
    eyebrow: 'Business operations',
    description: 'Build the estimate line by line—from recruiting and vacancy through ramp-up, knowledge transfer, and context recovery.',
    calculatorPath: '/tools/cost-of-turnover',
    calculatorLabel: 'Turnover cost calculator',
    author: { name: 'L.Bailey', role: 'Founder' },
    readingTime: '8 min read',
    listeningTime: '9 min listen',
    audioPath: '/article-review-narration/cost-of-employee-turnover.mp3',
    railPoints: ['Vacancy', 'Hiring', 'Ramp-up', 'Knowledge loss'],
  },
  {
    slug: 'cost-of-rework',
    title: 'How to Calculate the Cost of Rework',
    eyebrow: 'Business operations',
    description: 'Put a boundary around repeated work, then calculate labor, coordination, documented nonlabor cost, and the portion the organization can reasonably influence.',
    calculatorPath: '/tools/rework-cost-calculator',
    calculatorLabel: 'Rework cost calculator',
    author: { name: 'L.Bailey', role: 'Founder' },
    readingTime: '8 min read',
    listeningTime: '9 min listen',
    audioPath: '/article-review-narration/cost-of-rework.mp3',
    railPoints: ['Repeated labor', 'Coordination', 'Nonlabor cost', 'Influenceable share'],
  },
];
