"""initial schema from models

Revision ID: e0e77268ce38
Revises: 9ae3dc3062a6
Create Date: 2025-12-03 14:29:45.492858

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e0e77268ce38'
down_revision = '9ae3dc3062a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_miq_analyses_created")
    op.execute("DROP INDEX IF EXISTS idx_miq_analyses_thread_id")
    op.execute("DROP INDEX IF EXISTS idx_miq_messages_created")
    op.execute("DROP INDEX IF EXISTS idx_miq_messages_thread_id")
    op.execute("DROP INDEX IF EXISTS idx_miq_scenarios_created")
    op.execute("DROP INDEX IF EXISTS idx_miq_scenarios_thread_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_miq_scenarios_thread_id', 'miq_scenarios', ['thread_id'], unique=False)
    op.create_index('idx_miq_scenarios_created', 'miq_scenarios', ['created_at'], unique=False)
    op.create_index('idx_miq_messages_thread_id', 'miq_messages', ['thread_id'], unique=False)
    op.create_index('idx_miq_messages_created', 'miq_messages', ['created_at'], unique=False)
    op.create_index('idx_miq_analyses_thread_id', 'miq_analyses', ['thread_id'], unique=False)
    op.create_index('idx_miq_analyses_created', 'miq_analyses', ['created_at'], unique=False)
    # ### end Alembic commands ###
