"""create miq tables (messages/analyses/scenarios)

Revision ID: fe2e1a00739f
Revises: 520a20a83a54
Create Date: 2025-12-09 01:20:21.607990

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fe2e1a00739f'
down_revision = '520a20a83a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miq_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miq_analyses_analysis_id'), 'miq_analyses', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_miq_analyses_created_at'), 'miq_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_miq_analyses_session_id'), 'miq_analyses', ['session_id'], unique=False)
    op.create_index(op.f('ix_miq_analyses_thread_id'), 'miq_analyses', ['thread_id'], unique=False)
    op.create_table('miq_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miq_messages_created_at'), 'miq_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_miq_messages_session_id'), 'miq_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_miq_messages_thread_id'), 'miq_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_miq_messages_user_id'), 'miq_messages', ['user_id'], unique=False)
    op.create_table('miq_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('based_on', sa.String(length=64), nullable=True),
    sa.Column('deltas', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miq_scenarios_based_on'), 'miq_scenarios', ['based_on'], unique=False)
    op.create_index(op.f('ix_miq_scenarios_created_at'), 'miq_scenarios', ['created_at'], unique=False)
    op.create_index(op.f('ix_miq_scenarios_scenario_id'), 'miq_scenarios', ['scenario_id'], unique=True)
    op.create_index(op.f('ix_miq_scenarios_session_id'), 'miq_scenarios', ['session_id'], unique=False)
    op.create_index(op.f('ix_miq_scenarios_thread_id'), 'miq_scenarios', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_miq_scenarios_thread_id'), table_name='miq_scenarios')
    op.drop_index(op.f('ix_miq_scenarios_session_id'), table_name='miq_scenarios')
    op.drop_index(op.f('ix_miq_scenarios_scenario_id'), table_name='miq_scenarios')
    op.drop_index(op.f('ix_miq_scenarios_created_at'), table_name='miq_scenarios')
    op.drop_index(op.f('ix_miq_scenarios_based_on'), table_name='miq_scenarios')
    op.drop_table('miq_scenarios')
    op.drop_index(op.f('ix_miq_messages_user_id'), table_name='miq_messages')
    op.drop_index(op.f('ix_miq_messages_thread_id'), table_name='miq_messages')
    op.drop_index(op.f('ix_miq_messages_session_id'), table_name='miq_messages')
    op.drop_index(op.f('ix_miq_messages_created_at'), table_name='miq_messages')
    op.drop_table('miq_messages')
    op.drop_index(op.f('ix_miq_analyses_thread_id'), table_name='miq_analyses')
    op.drop_index(op.f('ix_miq_analyses_session_id'), table_name='miq_analyses')
    op.drop_index(op.f('ix_miq_analyses_created_at'), table_name='miq_analyses')
    op.drop_index(op.f('ix_miq_analyses_analysis_id'), table_name='miq_analyses')
    op.drop_table('miq_analyses')
    # ### end Alembic commands ###
